export type Produto = {
  id: number;
  nome: string;
  marca: string;
  preco: number;
  parcelas: number;
  badge: string;
  categoria: string;
  descricao: string;
  detalhes: string[];
  cor: string;
  imagemUrl?: string;
};

export type Categoria = {
  slug: string;
  nome: string;
  pluralNome: string;
  cor: string;
  corClara: string;
  descricao: string;
  emoji: string;
};

export const categorias: Categoria[] = [
  {
    slug: "sol",
    nome: "Sol",
    pluralNome: "Óculos de Sol",
    cor: "#f59e0b",
    corClara: "#fef3c7",
    descricao: "Proteção UV400 e estilo para todas as estações.",
    emoji: "☀️",
  },
  {
    slug: "grau",
    nome: "Grau",
    pluralNome: "Óculos de Grau",
    cor: "#06b6d4",
    corClara: "#cffafe",
    descricao: "Conforto e precisão visual para o seu dia a dia.",
    emoji: "👓",
  },
  {
    slug: "armacao",
    nome: "Armação",
    pluralNome: "Armações",
    cor: "#ec4899",
    corClara: "#fce7f3",
    descricao: "Designs autorais para quem busca exclusividade.",
    emoji: "✨",
  },
  {
    slug: "esportivo",
    nome: "Esportivo",
    pluralNome: "Linha Esportiva",
    cor: "#10b981",
    corClara: "#d1fae5",
    descricao: "Performance e resistência para quem vive em movimento.",
    emoji: "🏃",
  },
  {
    slug: "premium",
    nome: "Premium",
    pluralNome: "Coleção Premium",
    cor: "#8b5cf6",
    corClara: "#ede9fe",
    descricao: "Edições limitadas. Materiais nobres. Pura sofisticação.",
    emoji: "👑",
  },
];

export const produtos: Produto[] = [
  // ===== SOL (4) =====
  {
    id: 1,
    nome: "Wayfarer Classic",
    marca: "Ray-Ban",
    preco: 699,
    parcelas: 6,
    badge: "Mais vendido",
    categoria: "Sol",
    descricao: "Ícone atemporal. Armação acetato, proteção UV400, disponível em 8 cores.",
    detalhes: ["Proteção UV400", "Armação em acetato", "Lente mineral", "Disponível em 8 cores", "Garantia 12 meses"],
    cor: "#f59e0b",
    imagemUrl: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800&q=80",
  },
  {
    id: 2,
    nome: "Aviator Gold",
    marca: "Ray-Ban",
    preco: 1199,
    parcelas: 10,
    badge: "Clássico",
    categoria: "Sol",
    descricao: "O ícone aviador em metal dourado. Lentes G-15 originais com proteção total.",
    detalhes: ["Metal dourado", "Lentes G-15", "Proteção UV400", "Hastes ajustáveis", "Estojo premium"],
    cor: "#f59e0b",
    imagemUrl: "https://images.unsplash.com/photo-1574258495973-f010dfbb5371?w=800&q=80",
  },
  {
    id: 3,
    nome: "Cat-Eye Vintage",
    marca: "Versace",
    preco: 1499,
    parcelas: 12,
    badge: "Tendência",
    categoria: "Sol",
    descricao: "Formato felino atemporal. Acetato italiano e detalhes Medusa em ouro escovado.",
    detalhes: ["Acetato italiano", "Detalhes em ouro 18k", "Lente polarizada", "Edição numerada", "Garantia 24 meses"],
    cor: "#f59e0b",
    imagemUrl: "https://images.unsplash.com/photo-1508296695146-257a814070b4?w=800&q=80",
  },
  {
    id: 4,
    nome: "Pilot Mirror",
    marca: "Persol",
    preco: 899,
    parcelas: 8,
    badge: "Novo",
    categoria: "Sol",
    descricao: "Lente espelhada e armação leve em metal. Estilo aviador moderno.",
    detalhes: ["Lente espelhada", "Metal ultraleve", "Proteção UV400", "Antirreflexo", "Garantia 18 meses"],
    cor: "#f59e0b",
    imagemUrl: "https://images.unsplash.com/photo-1577803645773-f96470509666?w=800&q=80",
  },

  // ===== GRAU (4) =====
  {
    id: 5,
    nome: "Round Vintage",
    marca: "Oakley",
    preco: 799,
    parcelas: 8,
    badge: "Best-seller",
    categoria: "Grau",
    descricao: "Armação redonda em metal escovado. Conforto para uso prolongado.",
    detalhes: ["Metal escovado", "Hastes flex", "Compatível multifocal", "Antirreflexo grátis", "Garantia 24 meses"],
    cor: "#06b6d4",
    imagemUrl: "https://images.unsplash.com/photo-1591076482161-42ce6da69f67?w=800&q=80",
  },
  {
    id: 6,
    nome: "Holbrook Titanium",
    marca: "Oakley",
    preco: 1299,
    parcelas: 12,
    badge: "Tecnologia",
    categoria: "Grau",
    descricao: "Armação ultraleve em titânio. Ideal para quem usa óculos o dia inteiro.",
    detalhes: ["Titânio puro", "Apenas 12g", "Hipoalergênico", "Compatível multifocal", "Garantia 24 meses"],
    cor: "#06b6d4",
    imagemUrl: "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800&q=80",
  },
  {
    id: 7,
    nome: "Square Modern",
    marca: "Calvin Klein",
    preco: 749,
    parcelas: 6,
    badge: "Minimalista",
    categoria: "Grau",
    descricao: "Linhas geométricas e acabamento fosco. Para quem prefere o minimalismo.",
    detalhes: ["Acabamento fosco", "Acetato premium", "Lente antirrisco", "Compatível progressiva", "Garantia 18 meses"],
    cor: "#06b6d4",
    imagemUrl: "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&q=80",
  },
  {
    id: 8,
    nome: "Precision Flex",
    marca: "Oakley",
    preco: 979,
    parcelas: 10,
    badge: "Resistente",
    categoria: "Grau",
    descricao: "Material flexível indeformável. Resiste a impactos e ao uso intenso.",
    detalhes: ["Material flexível", "Resistente a impactos", "Leve e confortável", "Hastes 360°", "Garantia 18 meses"],
    cor: "#06b6d4",
    imagemUrl: "https://images.unsplash.com/photo-1473496169904-658ba7c44d8a?w=800&q=80",
  },

  // ===== ARMAÇÃO (4) =====
  {
    id: 9,
    nome: "Medusa Luxe",
    marca: "Versace",
    preco: 2199,
    parcelas: 12,
    badge: "Edição limitada",
    categoria: "Armacao",
    descricao: "Design italiano exclusivo. Detalhes dourados e acetato de alta resistência.",
    detalhes: ["Design italiano", "Detalhes em ouro 18k", "Acetato premium", "Edição limitada", "Certificado de autenticidade"],
    cor: "#ec4899",
    imagemUrl: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&q=80",
  },
  {
    id: 10,
    nome: "GV Rose Gold",
    marca: "Giorgio Armani",
    preco: 1899,
    parcelas: 12,
    badge: "Luxo",
    categoria: "Armacao",
    descricao: "Sofisticação em ouro rosê. Para quem não abre mão do refinamento.",
    detalhes: ["Ouro rosê 18k", "Acetato italiano", "Design exclusivo", "Peça numerada", "Caixa premium"],
    cor: "#ec4899",
    imagemUrl: "https://images.unsplash.com/photo-1620207418302-439b387441b0?w=800&q=80",
  },
  {
    id: 11,
    nome: "Octagon Italian",
    marca: "Prada",
    preco: 2499,
    parcelas: 12,
    badge: "Premium",
    categoria: "Armacao",
    descricao: "Formato octogonal em acetato veneziano. Peça de assinatura.",
    detalhes: ["Acetato veneziano", "Formato octogonal", "Hastes em metal", "Estojo Prada original", "Garantia 24 meses"],
    cor: "#ec4899",
    imagemUrl: "https://images.unsplash.com/photo-1610563166150-b34df4f3bcd6?w=800&q=80",
  },
  {
    id: 12,
    nome: "Acetate Black",
    marca: "Tom Ford",
    preco: 1599,
    parcelas: 12,
    badge: "Elegante",
    categoria: "Armacao",
    descricao: "Acetato preto profundo com hastes em metal escovado e logo dourado.",
    detalhes: ["Acetato preto premium", "Hastes em metal", "Logo em ouro", "Encaixe perfeito", "Garantia 18 meses"],
    cor: "#ec4899",
    imagemUrl: "https://images.unsplash.com/photo-1556015048-4d3aa10df74c?w=800&q=80",
  },

  // ===== ESPORTIVO (4) =====
  {
    id: 13,
    nome: "Radar Performance",
    marca: "Oakley",
    preco: 1099,
    parcelas: 10,
    badge: "Performance",
    categoria: "Esportivo",
    descricao: "Lente Prizm para esportes. Aderência total e visão otimizada para qualquer terreno.",
    detalhes: ["Tecnologia Prizm", "Lente intercambiável", "Antiembaçante", "Hastes Unobtainium", "Resistente a impactos"],
    cor: "#10b981",
    imagemUrl: "https://images.unsplash.com/photo-1614094082869-cd4e4b2905c7?w=800&q=80",
  },
  {
    id: 14,
    nome: "Active Run",
    marca: "Nike Vision",
    preco: 849,
    parcelas: 8,
    badge: "Corrida",
    categoria: "Esportivo",
    descricao: "Ultraleve para corrida e ciclismo. Não desliza nem com suor.",
    detalhes: ["Apenas 18g", "Pads de silicone", "Lente polarizada", "100% UV", "Garantia 12 meses"],
    cor: "#10b981",
    imagemUrl: "https://images.unsplash.com/photo-1556306535-0f09a537f0a3?w=800&q=80",
  },
  {
    id: 15,
    nome: "Crossfit Pro",
    marca: "Under Armour",
    preco: 999,
    parcelas: 10,
    badge: "Pro",
    categoria: "Esportivo",
    descricao: "Resistência militar para treinos intensos. Suporta quedas e suor.",
    detalhes: ["Padrão MIL-PRF-31013", "Antiembaçante", "Hastes flex", "Estojo rígido", "Garantia 24 meses"],
    cor: "#10b981",
    imagemUrl: "https://images.unsplash.com/photo-1567473810954-507d59716c25?w=800&q=80",
  },
  {
    id: 16,
    nome: "Cycling Edge",
    marca: "Rudy Project",
    preco: 1199,
    parcelas: 10,
    badge: "Ciclismo",
    categoria: "Esportivo",
    descricao: "Lentes ImpactRX para ciclistas. Aerodinâmica e ventilação otimizadas.",
    detalhes: ["Lentes ImpactRX", "Aerodinâmico", "Ventilação ativa", "Hastes ajustáveis", "Bolsa de microfibra"],
    cor: "#10b981",
    imagemUrl: "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=800&q=80",
  },

  // ===== PREMIUM (4) =====
  {
    id: 17,
    nome: "Diamond Edition",
    marca: "Cartier",
    preco: 4999,
    parcelas: 12,
    badge: "Exclusivo",
    categoria: "Premium",
    descricao: "Detalhes em diamante natural e ouro 18k. Edição limitada a 100 peças no mundo.",
    detalhes: ["Diamantes naturais", "Ouro 18k maciço", "Edição limitada (100 peças)", "Certificado", "Caixa de couro"],
    cor: "#8b5cf6",
    imagemUrl: "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=800&q=80",
  },
  {
    id: 18,
    nome: "Onyx Luxe",
    marca: "Tom Ford",
    preco: 3899,
    parcelas: 12,
    badge: "Premium",
    categoria: "Premium",
    descricao: "Acetato preto onyx polido com hastes em titânio escovado.",
    detalhes: ["Acetato onyx", "Titânio escovado", "Acabamento à mão", "Numeração única", "Garantia 5 anos"],
    cor: "#8b5cf6",
    imagemUrl: "https://images.unsplash.com/photo-1589642380614-4a8c2147b857?w=800&q=80",
  },
  {
    id: 19,
    nome: "Royal Crystal",
    marca: "Bulgari",
    preco: 5499,
    parcelas: 12,
    badge: "Royal",
    categoria: "Premium",
    descricao: "Cristais Swarovski e acabamento em ouro rosê. A peça mais sofisticada da casa.",
    detalhes: ["Cristais Swarovski", "Ouro rosê 18k", "Edição numerada", "Certificado Bulgari", "Caixa premium"],
    cor: "#8b5cf6",
    imagemUrl: "https://images.unsplash.com/photo-1592492152545-9695d3f473f4?w=800&q=80",
  },
  {
    id: 20,
    nome: "Master Limited",
    marca: "Lindberg",
    preco: 4299,
    parcelas: 12,
    badge: "Master",
    categoria: "Premium",
    descricao: "Engenharia dinamarquesa em titânio puro. Sem parafusos, sem soldas.",
    detalhes: ["Titânio puro grade 1", "Sem parafusos", "Sem soldas", "Apenas 1.9g por peça", "Garantia 10 anos"],
    cor: "#8b5cf6",
    imagemUrl: "https://images.unsplash.com/photo-1603899122634-f086ca5f5ddd?w=800&q=80",
  },
];

export const corMap: Record<string, string> = {
  "Ray-Ban": "#2c1f0e",
  "Oakley": "#06b6d4",
  "Versace": "#ec4899",
  "Giorgio Armani": "#b8914a",
  "Persol": "#f59e0b",
  "Calvin Klein": "#06b6d4",
  "Prada": "#ec4899",
  "Tom Ford": "#2c1f0e",
  "Nike Vision": "#10b981",
  "Under Armour": "#10b981",
  "Rudy Project": "#10b981",
  "Cartier": "#8b5cf6",
  "Bulgari": "#8b5cf6",
  "Lindberg": "#8b5cf6",
};
